### ISSUE TITLE
Paramétrage d'un modèle avec un fichier de config

### ISSUE THREAD

**Issue by vviers** [signaux-faibles/predictsignauxfaibles#8]
## Quoi

Il serait bon pour la reproducibilité de nos travaux de pouvoir définir un modèle via un fichier de configuration qui serait versionné

## Implémentation

- Un fichier [YAML](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html) `/models/1.0.0/model.yml` avec le format suivant :

```yaml
---
name: first_gam_model
version: 1.0.0
target: outcome
features:
  - feature_1
  - feature_2
  - feature_3
  - ...
batch_id: batch_mongo_db
train_on:
  start_date: 2015-01-01
  end_date: 2018-06-31
  sample_size: 1000000
predict_on:
  start_date: 2020-01-01
  end_date: 2021-01-31
...
```

(le format évoluera au fur et à mesure que le code sera développé)

- écrire les méthodes de classe `from_config_file()` dans `SFDataset` et dans les `SFModel`
